server:
  port: 3000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka

spring:
  application:
    name: manageserver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    cloud:
      bus:
        enabled: true
        trace:
          enabled: true