server:
  #ssl:
   # key-store: classpath:3381059_www.hitenproductservice.com.pfx
   # key-store-type: PKCS12
   # key-store-password: QPFOouPL
   # host: localhost
   # port: 5672
  port: 1002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka
spring:
  application:
    name: push