server:
    ssl:
      key-store: classpath:3381059_www.hitenproductservice.com.pfx
      key-store-type: PKCS12
      key-store-password: QPFOouPL
      host: localhost
      port: 5672
    port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka
spring:
  application:
    name: transaction
  datasource:
    read:
      url: jdbc:mysql://localhost:3306/transaction?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: lzj1122
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    write:
      url: jdbc:mysql://localhost:3306/transaction?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: lzj1122
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
