server:
  port: 4000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

spring:
  application:
    name: comsumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    cloud:
      bus:
        enabled: true
        trace:
          enabled: true
feign:
  hystrix:
    enabled: true